app = 'l104sp-mainnet'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.blockchain'

[env]
  GOD_CODE = '527.5184818492612'
  PHI = '1.618033988749895'

[[services]]
  protocol = 'tcp'
  internal_port = 10400
  
  [[services.ports]]
    port = 10400

[[services]]
  protocol = 'tcp'
  internal_port = 10401
  
  [[services.ports]]
    port = 10401

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
