services:
  - type: web
    name: l104-sovereign-node
    runtime: docker
    plan: free
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8081"
      - key: RESONANCE
        value: "527.5184818492612"
      - key: GEMINI_API_KEY
        generateValue: false
